In [1]:
x='Christopher Brooks'

In [2]:
print('Chris' in x)

True


In [3]:
x='aza'

In [4]:
print(3*x)

azaazaaza


In [5]:
name='Abdullaev Azamat'

In [6]:
print(name.split(' ')[0])

Abdullaev


In [7]:
nameArr = name.split(' ')

In [8]:
print(nameArr)

['Abdullaev', 'Azamat']


In [9]:
student_record = {'id': 'u1710008',
                  'name':'Abdullaev Azamat',
                  'gpa':4.47}

In [10]:
student_statement = '{} with Student ID of {}. He has GPA of {}'

In [12]:
print(student_statement.format(
    student_record['name'],
    student_record['id'],
    student_record['gpa']
))

Abdullaev Azamat with Student ID of u1710008. He has GPA of 4.47


In [13]:
import time

In [14]:
time.time()


1556278847.476927

In [15]:
time.clock()

7.052332894090533e-07

In [16]:
import datetime as dt


In [17]:
import time as tm

In [18]:
dtnow = dt.datetime.fromtimestamp(tm.time())

In [19]:
dtnow

datetime.datetime(2019, 4, 26, 16, 51, 19, 983198)

In [20]:
dtnow

datetime.datetime(2019, 4, 26, 16, 51, 19, 983198)

In [21]:
dtnow.year, dtnow.month, dtnow.day

(2019, 4, 26)

In [22]:
delta = dt.timedelta(days=10)

In [23]:
today = td.date().today


NameError: name 'td' is not defined

In [24]:
today = dt.date.today
today+delta

TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'datetime.timedelta'

In [25]:
today-delta

TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'datetime.timedelta'

In [26]:
today

<function date.today>

In [27]:
today = dt.date.today()

In [28]:
today+delta

datetime.date(2019, 5, 6)

In [29]:
today>today-delta


True

In [30]:
today>today+delta

False

In [31]:
class Student:
    department = 'School of Computer Science'
    def set_name(self,name):
        self.name = name
    def set_id(self,id):
        self.id=id

In [34]:
store1 = [12.5, 62.2, 42.1]
store2= [34.1, 64.6,23]
min(store2)

23

In [35]:
map(min,store1,store2)

In [36]:
my_function = lambda a,b,c: a+b+c

In [37]:
my_function(1,2,3)

6

In [38]:
list=[]
for number in range(0,1000):
    if number%2==0:
        list.append(number)
list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [39]:
list = [number for number in range(0,1000) if number%2==0]

In [40]:
list


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [41]:
listBy3 = [number for number in range(0,100) if number%3==0]

In [42]:
listBy3

[0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99]

In [43]:
import numpy as np

In [44]:
mylist = [1,2,3]
x= np.array(mylist)
x

array([1, 2, 3])

In [45]:
x[0]

1

In [46]:
mylist[0]

1

In [47]:
y=np.array([4,5,6])

In [48]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
np.shape(m)


(2, 3)

In [50]:
n=np.arange(0,30,2)

In [51]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [52]:
n.shape()

TypeError: 'tuple' object is not callable

In [53]:
np.shape

<function numpy.core.fromnumeric.shape>

In [54]:
n.shape

(15,)

In [55]:
np.ones(1,2)

TypeError: data type not understood

In [56]:
np

<module 'numpy' from 'D:\\INSTALL\\Anaconda\\lib\\site-packages\\numpy\\__init__.py'>

In [57]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [58]:
arr=np.ones((2,2))

In [59]:
arr[0][0]

1.0

In [60]:
arr[0]

array([ 1.,  1.])

In [61]:
arr.resize(1,4)

In [62]:
arr

array([[ 1.,  1.,  1.,  1.]])

In [63]:
np.linspace(0,4,9)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [64]:
np.linalg(1)

TypeError: 'module' object is not callable

In [65]:
np.eye(1)

array([[ 1.]])

In [66]:
%precision0


ERROR:root:Line magic function `%precision0` not found.


In [67]:
np.eye(100)

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [68]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [69]:
np.diag(2)

ValueError: Input must be 1- or 2-d.

In [70]:
z=[1,2,3]

In [71]:
np.diag(z)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [72]:
np.diag(z)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [73]:
z=[24,15,36,2,5,23,84]

In [74]:
np.diag(z)

array([[24,  0,  0,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0,  0,  0],
       [ 0,  0, 36,  0,  0,  0,  0],
       [ 0,  0,  0,  2,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0],
       [ 0,  0,  0,  0,  0, 23,  0],
       [ 0,  0,  0,  0,  0,  0, 84]])

In [75]:
np.array([1,23,4]*3)

array([ 1, 23,  4,  1, 23,  4,  1, 23,  4])

In [76]:
np.array([1,2,3],3)

TypeError: data type not understood

In [77]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [78]:
p=np.ones((2,3))

In [79]:
p


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [80]:
p=np.ones((2,3),int)

In [81]:
p

array([[1, 1, 1],
       [1, 1, 1]])

In [83]:
np.vstack([p,3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [3, 3, 3],
       [3, 3, 3]])

In [84]:
np.hstack([3])

array([3])

In [85]:
x=[1,2,3]

In [86]:
y=[-1,-2,-3]

In [87]:
x+y

[1, 2, 3, -1, -2, -3]

In [88]:
np.add(x,y)

array([0, 0, 0])

In [89]:
x.dot(y)

AttributeError: 'list' object has no attribute 'dot'

In [90]:
x=np.array(x)

In [91]:
y=np.array(y)

In [92]:
x.dot(y)

-14

In [93]:
x**2

array([1, 4, 9], dtype=int32)

In [94]:
z=np.array(x,x**2)

TypeError: data type not understood

In [95]:
x=np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

In [96]:
x=np.array([1,2,3])

In [97]:
z=np.array(x,x**2)

TypeError: data type not understood

In [98]:
z=np.array([x,x**2])

In [99]:
z

array([[1, 2, 3],
       [1, 4, 9]])

In [100]:
z.shape

(2, 3)

In [101]:
z.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [102]:
z.T

array([[1, 1],
       [2, 4],
       [3, 9]])

In [103]:
z.shape


(2, 3)

In [104]:
z=z.T


In [105]:
z.shape

(3, 2)

In [106]:
z.dtype

dtype('int32')

In [107]:
z=z.astype('f')

In [108]:
z.sum

<function ndarray.sum>

In [109]:
z.sum()

20.0

In [110]:
z.max()

9.0

In [111]:
z=z.astype('int')

In [112]:
z.mean()

3.3333333333333335

In [113]:
z.std()

2.7487370837451071

In [114]:
z

array([[1, 1],
       [2, 4],
       [3, 9]])

In [115]:
z.argmax()

5

# INDEXING/SLICING


In [116]:
s=np.arange(13)

In [117]:
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [118]:
s=np.arange(13)**2

In [119]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [120]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [121]:
s[0:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [122]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [123]:
a[0:7]

NameError: name 'a' is not defined

In [124]:
s[0:4]

array([0, 1, 4, 9], dtype=int32)

In [125]:
s[-1]

144

In [126]:
s[-2]

121

In [127]:
s[0::1]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

In [128]:
s[0::2]

array([  0,   4,  16,  36,  64, 100, 144], dtype=int32)

In [129]:
r=np.arange(36)

In [130]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [131]:
r.resize(6,6)

In [132]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [133]:
r[0][4]

4

In [134]:
r[2]

array([12, 13, 14, 15, 16, 17])

In [135]:
r[-1:1]

array([], shape=(0, 6), dtype=int32)

In [136]:
r[r>30]

array([31, 32, 33, 34, 35])

In [137]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [138]:
r.shape

(6, 6)

In [139]:
r=0

In [140]:
r

0

In [141]:
r=np.random()

TypeError: 'module' object is not callable

In [142]:
old = np.ones(2,2)

TypeError: data type not understood

In [143]:
old = np.ones(2)

In [144]:
old

array([ 1.,  1.])

In [145]:
old = np.array([[1,1],
              [1,1]])

In [146]:
old

array([[1, 1],
       [1, 1]])

In [147]:
new=old

In [148]:
new[0,:2]=0

In [149]:
print(old)

[[0 0]
 [1 1]]


In [150]:
new[0]+=1

In [151]:
old

array([[1, 1],
       [1, 1]])

In [152]:
new[0]+=24

In [153]:
old

array([[25, 25],
       [ 1,  1]])

In [154]:
test = np.random.randint(0,10,(4,4))

In [155]:
test

array([[3, 9, 1, 3],
       [4, 1, 3, 1],
       [8, 8, 1, 4],
       [2, 4, 3, 7]])

In [157]:
for row in test:
    print (row)

[3 9 1 3]
[4 1 3 1]
[8 8 1 4]
[2 4 3 7]


In [158]:
for i, row in enumerate(test):
    print('row',i,'is',row)

row 0 is [3 9 1 3]
row 1 is [4 1 3 1]
row 2 is [8 8 1 4]
row 3 is [2 4 3 7]
